### ISSUE TITLE
[Device] timeout

### ISSUE THREAD

**Issue by rvvaar** [AnsonCheng03/homebridge-dohome-switch#1]
Hi,
I have problem with configuration. I have all informations from DoHome app (where smart plug is working) but I got log info that device has been timeouted. I can use it via DoHome app.
That can be problem with "Subnet" address - what do you mean there? Network address? Subnet mask? Gateway address? Broadcast address? I think I've tried all but still got timeout :C

**Comment by AnsonCheng03** [comment]
Could you please let me know if you are using a Mac or a Windows computer?

**Comment by rvvaar** [comment]
Hi,
I’m using a Mac computer, Homebridge is an VM on ESXi.

**Comment by rvvaar** [comment]
So.. I've tried on Windows PC and it seems to work. :O
 What's the problem?

**Comment by AnsonCheng03** [comment]
When you click the On / Off button, homebridge will send a UDP package with an ASCII string 
```
cmd=ctrl&devices={_PRODUCTNAME_}&op={"cmd":5, "op":1}
``` 

If the device receives it successfully, it may reply with the string 
```
cmd=echo&dev=_DeviceName_&op={"res":0,"cmd":5,"stamps":0}
```

The device will show a timeout error if it could not receive any feedback from the DoHome device in 2.5 seconds.

------------------


You may fetch the packages from both homebridge and the DoHome plug via terminal by 
```
sudo tcpdump -i en0 -X -v 'udp port 6091'
```
Personally, I use the app ```UDP Terminal``` on AppStore since the terminal on Mac does not receive all packages. However, it is not free. (｡-_-｡)

Please verify whether the homebridge is sending any data.

**Comment by AnsonCheng03** [comment]
https://github.com/SmartArduino/DoHome/tree/master/protocol

Here are some resources on the UDP protocol that the DoHome plug used.

**Comment by rvvaar** [comment]
Seems to be fine rn 🙂
